---
service: emojo

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  stage: dev
  runtime: nodejs8.10
  region: eu-west-1

  environment:
    ACCESS_TOKEN: ${env:ACCESS_TOKEN}
    VERIFICATION_TOKEN: ${env:VERIFICATION_TOKEN}

functions:
  index:
    handler: src/handler.handler
    events:
      - http:
          path: slack/emoji
          method: POST

package:
  excludeDevDependencies: true

custom:
  serverless-offline:
    # dontPrintOutput: true
    port: ${env:WEBSERVER_PORT, '5020'}
