---
version: 2.1

jobs:
  build:
    working_directory: ~/emojo

    docker:
      - image: amazon/aws-sam-cli-build-image-nodejs14.x

    steps:
      - run: pwd
      - run: ls -la ~/emojo
      - run: npm install -g yarn
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn pruner-cli
      - run: |
          yarn serverless package \
            --stage production \
            --region eu-west-1
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - .serverless
            - serverless.yml

  deploy:
    working_directory: ~/emojo
    docker:
      - image: node:14-alpine3.12
    steps:
      - attach_workspace:
          at: ~/emojo
      - run: |
          node_modules/.bin/serverless deploy \
            --verbose \
            --stage production \
            --region eu-west-1 \
            --package .serverless

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
