---
version: 2.0

jobs:
  build:
    docker:
      - image: guyfedwards/alpine-node-git-bash
    branches:
      only:
        - master
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-dependencies-{{ checksum "yarn.lock" }}
            - yarn-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: yarn-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn lint
      - run: yarn test
