---
version: 2.0

orbs:
  yarn: artsy/yarn@0.1.4

jobs:
  build:
    working_directory: ~/emojo

    docker:
      - image: lambci/lambda:build-nodejs8.10

    steps:
      - name: install yarn
        command: |
          curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | \
            tee /etc/yum.repos.d/yarn.repo
          yum install yarn

      - yarn/update_dependencies
      - yarn/lint
      - yarn/test
      - yarn/run:
          script: serverless package

      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - .serverless
            - serverless.yml

  deploy:
    working_directory: ~/emojo
    docker:
      - image: guyfedwards/alpine-node-git-bash
    steps:
      - attach_workspace:
          at: ~/emojo
      - run: |
          node_modules/.bin/serverless deploy \
            --verbose \
            --stage production \
            --region eu-west-1 \
            --package .serverless

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
